echo off
echo .. Remote URL
echo ...............................
echo .
git remote -v
echo ...............................
echo .. Remote Branches
echo ...............................
echo .
git branch -r
echo ...............................
echo .. Local Branches
echo ...............................
echo .
git branch
echo ...............................
echo .. configuration .git\config 
echo ...............................
echo .
type .git\config
echo ...............................
echo .. most recent commit
echo ...............................
echo .
git --no-pager log -max-count=1
echo ...............................
echo .. current status
echo ...............................
echo .
git status
echo ...............................
pause
